baseURL = "http://www.zeroscope.com"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "ZeroScope - Managed Attribution Networking"
theme = "meghna-hugo"
summaryLength = 10

[taxonomies]
  author = "author"
  category = "categories"
  tag = "tags"

# Menu
[menu]
    [[menu.nav]]
    name = "About Us"
    URL = "about"
    weight = 2

    [[menu.nav]]
    name = "Jobs"
    URL = "jobs"
    weight = 3

    [[menu.nav]]
    name = "Internship"
    URL = "internship"
    weight = 4

    [[menu.nav]]
    name = "Contact"
    URL = "contact-us"
    weight = 5

# Site params
[params]
home= "Home"
logo = "images/logo.png"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
custom_css = ["css/custom.css"]

    # Banner Section
    [params.banner]
    enable = true
    bgImage = "images/slider/hero-area.jpg"
    icon = "tf-ion-play"
    heading = "Jobs @ SecDev"
    content= "Are you looking for an exciting opportunity that pushes you to the edge of innovative research and policy development?"
    btn = true
    btnText="Learn More"
    btnURL="jobs"

    # call to action
    [params.cta]
    enable = true
    title = "SecDev Group is looking for high-quality candidates"
    content = "Our work lives at the intersection of human behaviour and the digital future. Since 2006 weâ€™ve developed innovative technologies, solutions, and approaches to wicked problems in the toughest global environments."
    btnURL = "#"
    btnText = "Start a project with us"

    # counter
    [params.counter]
    enable = true
    bgImage = "images/backgrounds/bg-1.jpg"
        [[params.counter.counterItem]]
        title = "Happy Clients"
        icon = "tf-ion-android-happy"
        count = "320"

        [[params.counter.counterItem]]
        title = "Projects completed"
        icon = "tf-ion-archive"
        count = "565"

        [[params.counter.counterItem]]
        title = "Positive feedback"
        icon = "tf-ion-thumbsup"
        count = "95"

        [[params.counter.counterItem]]
        title = "Cups of Coffee"
        icon = "tf-ion-coffee"
        count = "2500"

    # footer
    [params.footer]
        copyright = "The SecDev Group"
        copyrightURL = "http://www.secdev.com"

        # social Icons
        [[params.footer.socialIcon]]
        icon = "tf-ion-social-facebook"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-twitter"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-google-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-youtube"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-linkedin"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-dribbble-outline"
        url = "#"

        [[params.footer.socialIcon]]
        icon = "tf-ion-social-pinterest-outline"
        url = "#"
